import { ProductType, FrameColor, GlassSpec, HandleFinish } from "./types";

export const PRODUCT_TYPES: ProductType[] = [
  {
    id: "slimline-sliding",
    name: "Slimline Sliding Window",
    category: "sliding",
    basePricePerSqFt: 520,
    description: "Ultra-thin 18mm sightlines with smooth horizontal sliding track.",
    defaultSightlineMm: 18,
    features: ["18mm Minimalist Stile", "Concealed Stainless Roller Track", "Soft-close Dampeners"],
  },
  {
    id: "lift-slide",
    name: "Lift & Slide Patio Door",
    category: "sliding",
    basePricePerSqFt: 650,
    description: "Heavy-duty panoramic elevation with lift mechanism for effortless operation up to 400kg.",
    defaultSightlineMm: 32,
    features: ["400kg Sash Load Capacity", "Flush Low-Threshold Track", "Lift-and-Lock Security"],
  },
  {
    id: "thermal-casement",
    name: "Thermal Break Casement Window",
    category: "casement",
    basePricePerSqFt: 580,
    description: "Polyamide thermal break insulation with European side-hinged outward sash.",
    defaultSightlineMm: 45,
    features: ["Polyamide Thermal Barrier", "Concealed Friction Stay Hinges", "Multi-Point Perimeter Locking"],
  },
  {
    id: "acoustic-partition",
    name: "Acoustic Glass Partition",
    category: "partition",
    basePricePerSqFt: 480,
    description: "Floor-to-ceiling interior glass wall system with minimal perimeter aluminium channel.",
    defaultSightlineMm: 12,
    features: ["Frameless Glass-to-Glass Joints", "48dB Acoustic Lamination", "Minimal U-Channel Perimeter"],
  },
];

export const FRAME_COLORS: FrameColor[] = [
  {
    id: "navy",
    name: "Anthracite Navy",
    hex: "#081C4B",
    secondaryHex: "#040E26",
    border: "#020718",
    textureType: "solid",
    priceMultiplier: 1.0,
  },
  {
    id: "matte-black",
    name: "Matte Black",
    hex: "#111827",
    secondaryHex: "#1F2937",
    border: "#000000",
    textureType: "anodized",
    priceMultiplier: 1.0,
  },
  {
    id: "anodized-silver",
    name: "Anodized Silver",
    hex: "#9CA3AF",
    secondaryHex: "#D1D5DB",
    border: "#4B5563",
    textureType: "brushed",
    priceMultiplier: 1.05,
  },
  {
    id: "bronze-copper",
    name: "Bronze Copper",
    hex: "#78350F",
    secondaryHex: "#92400E",
    border: "#451A03",
    textureType: "bronze",
    priceMultiplier: 1.12,
  },
  {
    id: "wood-grain",
    name: "Warm Teak Wood",
    hex: "#854D0E",
    secondaryHex: "#A16207",
    border: "#3F2200",
    textureType: "wood",
    priceMultiplier: 1.2,
  },
];

export const GLASS_SPECS: GlassSpec[] = [
  {
    id: "double-acoustic",
    name: "Double Glazed Acoustic (42dB)",
    shortDesc: "Acoustic PVB Interlayer + Argon Gas",
    multiplier: 1.2,
    fill: "rgba(224, 242, 254, 0.35)",
    stroke: "#38BDF8",
    edgeTint: "#0284C7",
    reflectionOpacity: 0.12,
    doubleEdge: true,
  },
  {
    id: "solar-low-e",
    name: "Solar Low-E Reflective Tint",
    shortDesc: "High Solar Heat Rejection & Soft Cyan Tint",
    multiplier: 1.25,
    fill: "rgba(186, 230, 253, 0.45)",
    stroke: "#0284C7",
    edgeTint: "#0369A1",
    reflectionOpacity: 0.25,
  },
  {
    id: "triple-thermal",
    name: "Triple Glazed Thermal Break",
    shortDesc: "Triple Glass Panes with Dual Cavity Seals",
    multiplier: 1.35,
    fill: "rgba(207, 250, 254, 0.4)",
    stroke: "#06B6D4",
    edgeTint: "#0891B2",
    reflectionOpacity: 0.15,
    doubleEdge: true,
  },
  {
    id: "clear-toughened",
    name: "Single Clear Toughened",
    shortDesc: "Ultra-Clear High-Transmittance Toughened Glass",
    multiplier: 1.0,
    fill: "rgba(240, 249, 255, 0.2)",
    stroke: "#BAE6FD",
    edgeTint: "#7DD3FC",
    reflectionOpacity: 0.08,
  },
  {
    id: "frosted-privacy",
    name: "Frosted Privacy Glass",
    shortDesc: "Acid-Etched Translucent Opaque Diffuser",
    multiplier: 1.15,
    fill: "rgba(241, 245, 249, 0.85)",
    stroke: "#94A3B8",
    pattern: "frosted",
    edgeTint: "#64748B",
    reflectionOpacity: 0.05,
  },
  {
    id: "bronze-tinted",
    name: "Bronze Tinted Glass",
    shortDesc: "Warm Amber Solar Protection Glazing",
    multiplier: 1.18,
    fill: "rgba(254, 243, 199, 0.45)",
    stroke: "#F59E0B",
    edgeTint: "#D97706",
    reflectionOpacity: 0.2,
  },
  {
    id: "grey-smoked",
    name: "Grey Smoked Glass",
    shortDesc: "Sleek Dark Charcoal Architectural Glass",
    multiplier: 1.18,
    fill: "rgba(71, 85, 105, 0.45)",
    stroke: "#475569",
    edgeTint: "#334155",
    reflectionOpacity: 0.22,
  },
  {
    id: "reflective-mirror",
    name: "Reflective Mirror Glass",
    shortDesc: "One-Way Privacy Metallic Mirror Finish",
    multiplier: 1.3,
    fill: "rgba(203, 213, 225, 0.7)",
    stroke: "#64748B",
    pattern: "mirror",
    edgeTint: "#475569",
    reflectionOpacity: 0.45,
  },
  {
    id: "reeded-fluted",
    name: "Reeded / Fluted Textured Glass",
    shortDesc: "Vertical Fluted Architectural Glass Profile",
    multiplier: 1.25,
    fill: "rgba(226, 232, 240, 0.5)",
    stroke: "#94A3B8",
    pattern: "reeded",
    edgeTint: "#64748B",
    reflectionOpacity: 0.1,
  },
  {
    id: "smart-switchable",
    name: "Smart Switchable Privacy Glass",
    shortDesc: "PDLC Electrochromic Instant Privacy Glazing",
    multiplier: 1.6,
    fill: "rgba(224, 242, 254, 0.5)",
    stroke: "#0284C7",
    pattern: "smart",
    edgeTint: "#0369A1",
    reflectionOpacity: 0.2,
  },
];

export const HANDLE_FINISHES: HandleFinish[] = [
  { id: "flush-pull", name: "Minimalist Flush Recessed Pull", hex: "#111827", priceAdd: 0 },
  { id: "architectural-lever", name: "Architectural Lever Handle", hex: "#374151", priceAdd: 1200 },
  { id: "matte-black-handle", name: "Matte Black Anodized Handle", hex: "#000000", priceAdd: 800 },
  { id: "brass-accent", name: "Brushed Satin Brass Handle", hex: "#D97706", priceAdd: 2200 },
];
